version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_linux:
    resource_class: small
    docker:
      - image: cimg/base:2022.11
    steps:
      - checkout
      - run:
          command: mkdir build
          name: make a build dir
      - run: 
          command: |
            cmake .. -DJACK_ASYNCHRONIZE_BUILD_EXAMPLES=on &&
            cmake --build .
          name: build examples
          working_directory: ./build

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build_linux